---
name: build

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# (none)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  schedule:
  # Build daily at 6:08am...
  - cron: '8 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.10'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        pip install --upgrade pip
        pip install --upgrade build
        pip install --requirement requirements.txt
        pip install --requirement build-requirements.txt
    - name: Test
      run: |
        pre-commit run --all-files
        pyroma .
    - name: Build
      run: |
        python -m build --sdist --wheel --outdir dist/
